<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <RootNamespace>PluginA</RootNamespace>
        <AssemblyName>PluginA</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <AdditionalFiles Include="localization.json"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\src\DynamicLocalization.Avalonia\DynamicLocalization.Avalonia.csproj"/>
        <ProjectReference Include="..\..\..\src\DynamicLocalization.Avalonia.SourceGenerator\DynamicLocalization.Avalonia.SourceGenerator.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"/>
    </ItemGroup>

</Project>
