using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace DynamicAvaloniaLocalization.SourceGenerator;

/// <summary>
///     Watches every "localization.json" additional file in the project and generates, for each
///     one, a resx-like static accessor class plus a <c>[ModuleInitializer]</c> that self-registers
///     with <c>DynamicAvaloniaLocalization.LocalizationManager.Instance</c>. Because module
///     initializers run whenever the CLR loads the containing assembly, the very same generated code
///     covers both a compile-time <c>ProjectReference</c> and a runtime
///     <c>Assembly.LoadFrom</c>/<c>AssemblyLoadContext</c> load.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class LocalizationIncrementalGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor InvalidJsonDescriptor = new(
        "DALOC001",
        "Invalid localization.json",
        "Failed to parse '{0}': {1}",
        "DynamicAvaloniaLocalization.SourceGenerator",
        DiagnosticSeverity.Error,
        true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var localizationFiles = context.AdditionalTextsProvider
            .Where(static file => IsLocalizationFile(file.Path))
            .Select(static (file, ct) => (file.Path, Text: file.GetText(ct)?.ToString()))
            .Where(static x => x.Text is not null);

        var assemblyName = context.CompilationProvider.Select(static (c, _) => c.AssemblyName ?? "Module");

        var pipeline = localizationFiles.Combine(assemblyName);

        context.RegisterSourceOutput(pipeline, static (spc, pair) =>
        {
            var ((path, text), moduleName) = pair;
            Generate(spc, path, text!, moduleName);
        });
    }

    private static bool IsLocalizationFile(string path)
    {
        return string.Equals(Path.GetFileName(path), "localization.json", StringComparison.OrdinalIgnoreCase);
    }

    private static void Generate(SourceProductionContext context, string path, string json, string moduleName)
    {
        List<JsonLocalizationEntry> entries;
        try
        {
            entries = MinimalJsonParser.ParseEntries(json);
        }
        catch (FormatException ex)
        {
            context.ReportDiagnostic(Diagnostic.Create(InvalidJsonDescriptor, Location.None, path, ex.Message));
            return;
        }

        var identifier = SanitizeToIdentifier(moduleName);
        var ns = $"{identifier}.Generated";
        var className = $"{identifier}Localization";
        var moduleInitializerClassName = $"{identifier}LocalizationModule";

        var source = BuildSource(ns, className, moduleInitializerClassName, moduleName, entries);
        context.AddSource($"{identifier}.Localization.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static string BuildSource(
        string ns,
        string className,
        string moduleInitializerClassName,
        string moduleName,
        List<JsonLocalizationEntry> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Regenerated from localization.json by DynamicAvaloniaLocalization.SourceGenerator.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();

        sb.AppendLine($"internal static class {moduleInitializerClassName}");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    internal static void Register()");
        sb.AppendLine("    {");
        sb.AppendLine(
            $"        global::DynamicAvaloniaLocalization.LocalizationManager.Instance.RegisterModule({Literal(moduleName)}, new global::DynamicAvaloniaLocalization.LocalizationEntry[]");
        sb.AppendLine("        {");
        foreach (var entry in entries)
        {
            sb.Append("            new global::DynamicAvaloniaLocalization.LocalizationEntry(");
            sb.Append(Literal(entry.Key));
            sb.Append(", new global::System.Collections.Generic.Dictionary<string, string>{");
            foreach (var value in entry.Values)
                sb.Append(' ').Append('[').Append(Literal(value.Key)).Append("] = ").Append(Literal(value.Value))
                    .Append(',');

            sb.AppendLine(" }),");
        }

        sb.AppendLine("        });");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine(
            $"/// <summary>Resx-like accessors for the \"{moduleName}\" localization module. Each property always reflects the current locale.</summary>");
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");
        sb.AppendLine($"    public const string ModuleName = {Literal(moduleName)};");
        sb.AppendLine();
        foreach (var entry in entries)
        {
            var propertyName = SanitizeToIdentifier(entry.Key);
            sb.AppendLine(
                $"    public static string {propertyName} => global::DynamicAvaloniaLocalization.LocalizationManager.Instance.Get(ModuleName, {Literal(entry.Key)});");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string Literal(string value)
    {
        return SymbolDisplay.FormatLiteral(value, true);
    }

    private static string SanitizeToIdentifier(string value)
    {
        if (string.IsNullOrEmpty(value))
        {
            return "_";
        }

        var sb = new StringBuilder(value.Length);
        foreach (var c in value) sb.Append(char.IsLetterOrDigit(c) ? c : '_');

        if (sb[0] != '_' && !char.IsLetter(sb[0]))
        {
            sb.Insert(0, '_');
        }

        return sb.ToString();
    }
}